# Generated by Django 3.2.3 on 2022-01-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_alter_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('correct_ans', models.CharField(max_length=250)),
                ('explanation', models.TextField(max_length=500)),
                ('option', models.ManyToManyField(to='mcq.Option')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_set',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Question_Set',
        ),
        migrations.AddField(
            model_name='question_sets',
            name='question',
            field=models.ManyToManyField(to='mcq.Questions'),
        ),
    ]
